services:
  - type: web
    name: stockmaster
    env: docker
    region: ohio
    plan: free
    healthCheckPath: /api/v1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_CA_CERT
        value: ca-cert.pem
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 8h
      - key: NODE_VERSION
        value: 20
